#!/bin/bash

# --- Configuration Variables ---
MAILRISE_HOST="192.168.0.4"
MAILRISE_PORT="8025"
# Nullmailer remote config format: host protocol [options]
# We construct this line for the configuration file
NULLMAILER_REMOTE_CONFIG="${MAILRISE_HOST} smtp --port=${MAILRISE_PORT}"

# --- Check for root privileges ---
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root (use sudo)."
   exit 1
fi

echo "🚀 Starting Nullmailer installation and configuration..."

# 1. Remove Postfix (Conflict Resolution)
# Nullmailer cannot run alongside Postfix. We must remove Postfix first.
if dpkg -l | grep -q postfix; then
    echo "--- Removing conflicting Postfix installation ---"
    DEBIAN_FRONTEND=noninteractive apt-get purge -y postfix
    DEBIAN_FRONTEND=noninteractive apt-get autoremove -y
fi

# 2. Install Nullmailer
echo "--- Installing Nullmailer ---"
# We pre-seed the mailname to avoid interactive prompts, though we overwrite it later.
echo "nullmailer shared/mailname string $(hostname -f)" | debconf-set-selections
DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y nullmailer mailutils

if [ $? -ne 0 ]; then
    echo "❌ Error: Nullmailer installation failed."
    exit 1
fi

# 3. Configure Nullmailer
echo "--- Configuring Nullmailer ---"

# Set the system mail name (FQDN)
# This defines the domain part of email addresses generated by this host (e.g., @pve.local)
SYSTEM_MAIL_NAME=$(hostname -f)
echo "${SYSTEM_MAIL_NAME}" > /etc/mailname
echo "${SYSTEM_MAIL_NAME}" > /etc/nullmailer/me
echo "${SYSTEM_MAIL_NAME}" > /etc/nullmailer/defaultdomain

# Configure the remote relay (Mailrise)
# Overwrites /etc/nullmailer/remotes with our Mailrise host details
echo "${NULLMAILER_REMOTE_CONFIG}" > /etc/nullmailer/remotes
chmod 600 /etc/nullmailer/remotes

# Optional: Configure adminaddr
# If set, mail sent to 'root' locally is rewritten to this address.
# If empty, mail to 'root' goes to 'root@${SYSTEM_MAIL_NAME}'
# Since we are relaying to Mailrise, keeping it empty or setting it to root is fine.
# echo "root@${SYSTEM_MAIL_NAME}" > /etc/nullmailer/adminaddr

# 4. Restart Nullmailer Service
echo "--- Restarting Nullmailer Service ---"
systemctl restart nullmailer

if [ $? -ne 0 ]; then
    echo "❌ Error: Nullmailer service restart failed."
    exit 1
fi

# 5. Verification and Test
echo "--- Nullmailer Configuration Complete ---"
echo "✅ Nullmailer configured to relay mail to: **${MAILRISE_HOST}:${MAILRISE_PORT}**"
echo ""

# Test Email
TEST_RECIPIENT="your_test_email@example.com"
echo "Attempting to send a test email to **${TEST_RECIPIENT}**..."
echo "This is a test email from the Nullmailer setup script." | mail -s "Nullmailer Mailrise Setup Test" ${TEST_RECIPIENT}

echo "--- Setup Finished ---"
echo "Check logs with: journalctl -u nullmailer -f"
echo "You should see a 'success' message connecting to ${MAILRISE_HOST}."
